######################################################################
#
# File name : gps_wave.do
# Created on: Sat Jul 08 18:53:33 +0800 2017
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
