######################################################################
#
# File name : gps_simulate.do
# Created on: Sat Jul 08 18:53:33 +0800 2017
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L dist_mem_gen_v8_0_11 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.gps xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {gps_wave.do}

view wave
view structure
view signals

do {gps.udo}

run 1000ns
