######################################################################
#
# File name : uart.udo
# Created on: Sat Jul 08 16:42:17 +0800 2017
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
