######################################################################
#
# File name : uart_simulate.do
# Created on: Tue Jul 11 20:36:53 +0800 2017
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L fifo_generator_v13_1_4 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.uart xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {uart_wave.do}

view wave
view structure
view signals

do {uart.udo}

run 1000ns
