######################################################################
#
# File name : uart_compile.do
# Created on: Tue Jul 11 20:36:51 +0800 2017
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech64_10.5\\win64\\vlib work
D:\\modeltech64_10.5\\win64\\vlib msim

D:\\modeltech64_10.5\\win64\\vlib msim/xil_defaultlib

D:\\modeltech64_10.5\\win64\\vmap xil_defaultlib msim/xil_defaultlib

D:\\modeltech64_10.5\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../GPS_test.srcs/sources_1/new/gps.v" \
"../../../GPS_test.srcs/sources_1/new/uart.v" \
"../../../GPS_test.srcs/sources_1/new/SPI.v" \
"../../../GPS_test.srcs/sources_1/ip/fifo/sim/fifo.v" \


# compile glbl module
D:\\modeltech64_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

