######################################################################
#
# File name : uart_wave.do
# Created on: Tue Jul 11 20:36:53 +0800 2017
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
