# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin.xdc

# XDC: new/timing.xdc

# IP: ip/fifo/fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo || ORIG_REF_NAME==fifo}]
