# 
# Synthesis run script generated by Vivado
# 

set_param tcl.collectionResultDisplayLimit 0
set_param simulator.modelsimInstallPath D:/modeltech64_10.5/win64
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/FPGA/Xilinx/projects/GPS_test/GPS_test.cache/wt [current_project]
set_property parent.project_path E:/FPGA/Xilinx/projects/GPS_test/GPS_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/FPGA/Xilinx/projects/GPS_test/GPS_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/FPGA/Xilinx/projects/GPS_test/GPS_test.srcs/sources_1/new/gps.v
  E:/FPGA/Xilinx/projects/GPS_test/GPS_test.srcs/sources_1/new/uart.v
  E:/FPGA/Xilinx/projects/GPS_test/GPS_test.srcs/sources_1/new/SPI.v
}
read_ip -quiet E:/FPGA/Xilinx/projects/GPS_test/GPS_test.srcs/sources_1/ip/fifo/fifo.xci
set_property used_in_implementation false [get_files -all e:/FPGA/Xilinx/projects/GPS_test/GPS_test.srcs/sources_1/ip/fifo/fifo.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/Xilinx/projects/GPS_test/GPS_test.srcs/sources_1/ip/fifo/fifo_ooc.xdc]
set_property is_locked true [get_files E:/FPGA/Xilinx/projects/GPS_test/GPS_test.srcs/sources_1/ip/fifo/fifo.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/FPGA/Xilinx/projects/GPS_test/GPS_test.srcs/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files E:/FPGA/Xilinx/projects/GPS_test/GPS_test.srcs/constrs_1/new/pin.xdc]

read_xdc E:/FPGA/Xilinx/projects/GPS_test/GPS_test.srcs/constrs_1/new/timing.xdc
set_property used_in_implementation false [get_files E:/FPGA/Xilinx/projects/GPS_test/GPS_test.srcs/constrs_1/new/timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top gps -part xc7a100tfgg484-2


write_checkpoint -force -noxdef gps.dcp

catch { report_utilization -file gps_utilization_synth.rpt -pb gps_utilization_synth.pb }
